In [18]:
# min cost flow 

G=[-1]*MAX_V
prevv=[-1]*MAX_V
preve=[-1]*MAX_V

class Edge:
    def __init__(self,to,cap,cost,rev):
        self.to=to
        self.cap=cap
        self.cost=cost
        self.rev=rev
        
def add_edge(fro,to,cap,cost):
    G[fro].append(Edge(to,cap,cost,len(G[to])))
    G[to].append(Edge(fro,0,-cost,len(G[fro])-1))
    
def min_cost_flow(s,t,f):
    res=0
    h=[0]*V
    while f>0:
        heap=[]
        dist=[float('inf')]*V
        dist[s]=0
        heapq.heappush(heap,(0,s)) #(dist, vertex)
        while heap:
            d,v=heapq.heappop(heap)
            if dist[v]<d: continue 
            for i in range(len(G[v])):
                e=G[v][i]
                if e.cap>0 and dist[e.to]>dist[v]+e.cost+h[v]-h[e.to]:
                    dist[e.to]=dist[v]+e.cost+h[v]-h[e.to]
                    prevv[e.to]=v
                    preve[e.to]=i
                    heapq.heappush((dist[e.to],e.to))
        if dist[t]==float('inf'):
            return -1
        for v in range(V):
            h[v]+=dist[v]
        d=f
        v=t
        while v!=s:
            d=min(d,G[prevv[v]][preve[v]].cap)
            v=prevv[v]
        f-=d
        res+=d*h[t]
        v=t
        while v!=s:
            e=G[prevv[v]][preve[v]]
            e.cap-=d
            G[v][e.rev].cap+=d
            v=prevv[v]
    return res

NameError: name 'MAX_V' is not defined

In [24]:
import heapq
inpt=iter(['4 5',
'1 2 1',
'2 3 1',
'3 4 1',
'1 3 2',
'2 4 2'])
N,M=tuple(map(int,next(inpt).split()))
V=N+1
G=[[] for _ in range(V)]


class Edge:
    def __init__(self,to,cap,cost,rev):
        self.to=to
        self.cap=cap
        self.cost=cost
        self.rev=rev
        
def add_edge(fro,to,cap,cost):
    G[fro].append(Edge(to,cap,cost,len(G[to])))
    G[to].append(Edge(fro,0,-cost,len(G[fro])-1))
    
def min_cost_flow(s,t,f):
    prevv=[-1]*V
    preve=[-1]*V
    res=0
    h=[0]*V
    while f>0:
        heap=[]
        dist=[float('inf')]*V
        dist[s]=0
        heapq.heappush(heap,(0,s)) #(dist, vertex)
        while heap:
            d,v=heapq.heappop(heap)
            if dist[v]<d: continue 
            for i in range(len(G[v])):
                e=G[v][i]
                if e.cap>0 and dist[e.to]>dist[v]+e.cost+h[v]-h[e.to]:
                    dist[e.to]=dist[v]+e.cost+h[v]-h[e.to]
                    prevv[e.to]=v
                    preve[e.to]=i
                    heapq.heappush(heap,(dist[e.to],e.to))
        if dist[t]==float('inf'):
            return -1
        for v in range(V):
            h[v]+=dist[v]
        d=f
        v=t
        while v!=s:
            d=min(d,G[prevv[v]][preve[v]].cap)
            v=prevv[v]
        f-=d
        res+=d*h[t]
        v=t
        while v!=s:
            e=G[prevv[v]][preve[v]]
            e.cap-=d
            G[v][e.rev].cap+=d
            v=prevv[v]
    return res

for _ in range(M):
    u,v,c=tuple(map(int,next(inpt).split()))
    add_edge(u,v,1,c)
    add_edge(v,u,1,c)
print (min_cost_flow(1,N,2))

6


In [29]:
for i,u in enumerate(G):
    for e in u :
        print (i,e.to,e.cap,e.cost,e.rev)
        

1 2 0 1 0
1 2 0 -1 1
1 3 0 2 4
1 3 0 -2 5
2 1 1 -1 0
2 1 1 1 1
2 3 1 1 0
2 3 0 -1 1
2 4 0 2 2
2 4 0 -2 3
3 2 0 -1 2
3 2 1 1 3
3 4 0 1 0
3 4 0 -1 1
3 1 1 -2 2
3 1 1 2 3
4 3 1 -1 2
4 3 1 1 3
4 2 1 -2 4
4 2 1 2 5


In [ ]:
# bipartite matching 
G=[[] for _ in range(MAX_V)]
used=[False]*MAX_V
match=[-1]*MAX_V
def add_edge(u,v):
    G[u].append(v)
    G[v].append(u)
def dfs(v):
    used[v]=True
    for i in range(len(G[v])):
        u=G[v][i]
        w=match[u]
        if w<0 or (not used[w] and dfs(w)):
            match[v]=u
            match[u]=v
            return True
    return False
def bipartite_matching():
    res=0
    for v in range(MAX_V):
        if match[v]<0:
            used=[False]*MAX_V
            if dfs(v):res+=1 
    return res 

In [4]:
# ASTEROID POJ 3041 
# 最小顶点覆盖： 每个边都至少与其中一个顶点相交 
# 二分图中 最小顶点覆盖数= 最大匹配数 
# after max flow, s 到不了的u +s 到的了的 v


# bipartite matching 

def add_edge(u,v):
    G[u].append(v)
    G[v].append(u)
def dfs(v):
    used[v]=True
    for i in range(len(G[v])):
        u=G[v][i]
        w=match[u]
        if w<0 or (not used[w] and dfs(w)):
            match[v]=u
            match[u]=v
            return True
    return False
def bipartite_matching():
    res=0
    for v in range(MAX_V):
        if match[v]<0:
            used=[False]*MAX_V
            if dfs(v):res+=1 

    return res 


N,K=tuple(map(int,input().split()))
MAX_V=2*N
G=[[] for _ in range(MAX_V)]
used=[False]*MAX_V
match=[-1]*MAX_V

for _ in range(K):
	u,v=tuple(map(int,input().split()))
	add_edge(u-1,N+v-1)
res=bipartite_matching()

3 4
1 1 
1 3
2 2
3 2
2


In [12]:
inpt=iter(['5 5','XXDXX','X...X','D...X','X...D','XXXXX'])

In [26]:
inpt=iter(['5 5','XDXXX','X.X.D','XX.XX','D.X.X','XXXDX'])
import collections 
# Evacuation poj 3057 
R,C=tuple(map(int,next(inpt).split()))
people=[]
door=[]
graph=[]
for i in range(R):
    line=next(inpt)
    graph.append(line)
    for j,c in enumerate(line):
        if c=='D':
            door.append((i,j))
        if c=='.':
            people.append((i,j))
v_hash=dict()
for i,p in enumerate(people):
    v_hash[p]=i
for i,d in enumerate(door):
    v_hash[d]=i+len(people)


dist=collections.defaultdict(list)

def bfs(dx,dy):
    visited=[[False]*C for _ in range(R)]
    t=0
    DIRS=[(0,1),(1,0),(0,-1),(-1,0)]
    q=collections.deque()
    q.append((dx,dy))
    while q:
        cur_x,cur_y=q.popleft()
        visited[cur_x][cur_y]=True
        t+=1
        for u,v  in DIRS:
            if 0<= cur_x+u<R and 0<=cur_y+v<C and \
            graph[cur_x+u][cur_y+v]=='.' and not visited[cur_x+u][cur_y+v]:
                q.append((cur_x+u,cur_y+v))
                dist[t].append((v_hash[dx,dy],v_hash[cur_x+u,cur_y+v]))
    return 

# find the distance of each person to each door 
for dx,dy in door:
    bfs(dx,dy)  


MAX_V=len(people)+len(door)

MAX_T=max(dist.keys())

# bipartite matching 
def add_edge(u,v):
    G[u].append(v)
    G[v].append(u)
def dfs(v):
    used[v]=True
    for i in range(len(G[v])):
        u=G[v][i]
        w=match[u]
        if w<0 or (not used[w] and dfs(w)):
            match[v]=u
            match[u]=v
            return True
    return False

t=1
res=0
while 1:
    #for every new second rematch newly escapable people with doors  
    G=[[] for _ in range(MAX_V)]
    match=[-1]*MAX_V
    for u,v in dist[t]:
        add_edge(u,v)
    for u,v in dist[t]:
        if match[u]<0:
            used=[False]*MAX_V
            if dfs(u):res+=1
        if match[v]<0:
            used=[False]*MAX_V
            if dfs(v):res+=1

    print (t,res)
    if res==len(people): 
        print (t)
        break
    if t==MAX_T:
        print ('impossible')
        break
    t+=1
        

1 4
impossible


In [1]:
from Dinic import Dinic

In [13]:
inpt=iter(['4 3 3','2 2 1 2 3 1','2 2 2 3 1 2','2 2 1 3 1 2','2 1 1 3 3'])
N,F,D=tuple(map(int,next(inpt).split()))
dinic=Dinic(2+F+D+N*2)
source=0
sink=1+F+D+N*2
for food in range(1,F+1):
    dinic.add_edge(source,food,1)
for drink in range(F+1,F+1+D):
    dinic.add_edge(drink,sink,1)
for i in range(1,N+1):
    dinic.add_edge(F+D+i,F+D+N+i,1)
for i in range(1,N+1):
    line=list(map(int,next(inpt).split()))
    f,d=line[:2]
    for food in line[2:2+f]:
        dinic.add_edge(food,F+D+i,1)
    for drink in line[-d:]:
        dinic.add_edge(F+D+N+i,drink+F,1)
max_flow=dinic.max_flow(source,sink)
print (max_flow)

3


In [11]:
max_flow=dinic.max_flow(source,sink)

In [12]:
max_flow

3

In [17]:
from Dinic import Dinic
inpt=iter(['3 1',
'1 10',
'2 10',
'10 3',
'2 3 1000'])
N,M=tuple(map(int,next(inpt).split()))
dinic=Dinic(N+2)
source=0
sink=N+1
for i in range(1,N+1):
	a,b=tuple(map(int,next(inpt).split()))
	dinic.add_edge(source,i,a)
	dinic.add_edge(i,sink,b)
for _ in range(M):
	a,b,w=tuple(map(int,next(inpt).split()))
	dinic.add_edge(a,b,w)
	dinic.add_edge(b,a,w)
print (dinic.max_flow(source,sink))

13


In [37]:
import numpy as np
p1=np.array((0,0))
p2=np.array((3,3))
q=np.array((1,1))
np.cross(p1-q,p2-q)
np.dot(p1-q,p2-q)

-4

In [52]:
p1=(0,0)
p2=(3,3)
q=(3,3)
p1,p2,q=tuple(map(np.array,(p1,p2,q)))

In [56]:
np.cross(p1-q,p2-q)

array(0)

In [57]:
np.dot(p1-q,p2-q)

0

In [58]:
p1=(0,3)
p2=(3,3)
q1=(0,0)
q2=(3,0)
p1,p2,q1,q2=tuple(map(np.array,(p1,p2,q1,q2)))

In [62]:
np.cross(q2-q1,q1-p1)/np.cross(q2-q1,p2-p1)*(p2-p1)+p1

array([1.5, 1.5])

In [61]:
0.5*(p2-p1)+p1

array([1.5, 1.5])

In [64]:

def intersection(p1,p2,q1,q2):
	# calculate the intersection point of segment p1-p2 and q1-q2 
	p1,p2,q1,q2=tuple(map(np.array,(p1,p2,q1,q2)))
    if np.cross(q2-q1,p2-p1)==0: 
        # parallel lines 
        return None 
	return np.cross(q2-q1,q1-p1)/np.cross(q2-q1,p2-p1)*(p2-p1)+p1

In [66]:
p1=(0,3)
p2=(3,1)
q1=(0,0)
q2=(3,0)
intersection(p1,p2,q1,q2)

array([4.5, 0. ])

In [109]:
# jack straws poj 1127 
inpt=iter([
'7',
'1 6 3 3 ',
'4 6 4 9 ',
'4 5 6 7 ',
'1 4 3 5 ',
'3 5 5 5 ',
'5 2 6 3 ',
'5 4 7 2' ,
'1 4 ',
'1 6 ',
'3 3 ',
'6 7 ',
'2 3 ',
'1 3 ',
'0 0'
])


# geometry functions 
import numpy as np

class UF:
    def __init__(self,n):
        self.parent=[i for i in range(n)]
        self.rank=[0]*n
        self.cnt=n
    def find(self,x):
        p=self.parent[x]
        if p==x: return x
        else: self.parent[x]=self.find(p)
        return self.parent[x]
    def union(self,x,y):
        x=self.find(x)
        y=self.find(y)
        if x==y: return 
        if self.rank[x]<self.rank[y]:
            self.parent[x]=y
        else:
            self.parent[y]=x
            if self.rank[x]==self.rank[y]: self.rank[x]+=1 
        self.cnt-=1 
    def same(self,x,y):
        return self.find(x)==self.find(y)

# geometry functions 
import numpy as np
eps=0.00001


def on_seg(p1,p2,q):
    # whether point q is on segment p1-p2 (including pint p1 and p2 )
    p1,p2,q=tuple(map(np.array,(p1,p2,q)))
    return abs(np.cross(p1-q,p2-q)-0)<eps and np.dot(p1-q,p2-q)<=0

def intersection(p1,p2,q1,q2):
    # calculate the intersection point of segment p1-p2 and q1-q2 
    p1,p2,q1,q2=tuple(map(np.array,(p1,p2,q1,q2)))
    if np.cross(q2-q1,p2-p1)==0: 
        # parallel lines 
        return None 
    return np.cross(q2-q1,q1-p1)/np.cross(q2-q1,p2-p1)*(p2-p1)+p1

def is_connected(p1,p2,q1,q2):
    inter=intersection(p1,p2,q1,q2)
    if inter is None: return False 
    else:
        return on_seg(p1,p2,inter) and on_seg(q1,q2,inter)



N=int(next(inpt))
uf=UF(N+1)
lines=[0]
for i in range(1,N+1):
    x1,y1,x2,y2=tuple(map(int,next(inpt).split()))
    for j in range(1,i):
        q1,q2=lines[j]
        if is_connected((x1,y1),(x2,y2),q1,q2):
            print (i,j)
            uf.union(j,i)
    lines.append(((x1,y1),(x2,y2)))
while 1:
    u,v=tuple(map(int,next(inpt).split()))
    if u==v==0: break 
    if uf.same(u,v):
        print ('CONNECTED')
    else:
        print ('NOT CONNECTED')

4 1
5 3
5 4
7 6
CONNECTED
NOT CONNECTED
CONNECTED
CONNECTED
NOT CONNECTED
CONNECTED


In [101]:
p1,p2,q1,q2=(4, 5), (6, 7), (4, 6) ,(4, 9)

In [102]:
p1,p2,q1,q2=tuple(map(np.array,(p1,p2,q1,q2)))
np.cross(q2-q1,p2-p1)

array(-6)

In [103]:
inter=intersection(p1,p2,q1,q2)

In [104]:
inter

array([4., 5.])

In [93]:
q=inter

In [106]:
np.cross(p1-q,p2-q)

array(0.)

In [107]:
np.dot(p1-q,p2-q)

19.591836734693874

In [105]:
on_seg(p1,p2,inter)

True

In [121]:
## coneology poj 2932
#平面扫描
inpt=iter([
'5',
'1 0 -2',
'3 0 3',
'10 0 0',
'1 0 1.5',
'10 50 50'
    ])
N=int(next(inpt))
y_bounds=dict()
points=[]
for i in range(1,N+1):
    r,p1,p2=tuple(map(float,next(inpt).split()))
    points.append((p1-r,i))
    points.append((p1+r,i))
    y_bounds[i]=((p2-r,p2+r))
points.sort() 
res=[]
not_res=set()
scan=set()
#print (points)
#print (y_bounds)

def is_inside(i,circle):
    return y_bounds[circle][0]<y_bounds[i][0] and y_bounds[circle][1]>y_bounds[i][1]
for x,i in points:
    #print (scan, res, not_res)
    if i in not_res: continue 
    if i in scan: # at the right point of circle i
        scan.remove(i)
    elif len(scan)>0 and any(is_inside(i,circle) for circle in scan):
        not_res.add(i)
    else: 
        scan.add(i)
        res.append(i)
print (res)

[3, 5]


In [158]:
def graham_scan(points):
    #O(nlogn)
    '''Graham scan to find upper and lower convex hulls of a set of 2d points.'''
    U = []
    L = []
    points.sort()
    for p in points:
        while len(U) > 1 and orientation(U[-2],U[-1],p) <= 0: U.pop()
        while len(L) > 1 and orientation(L[-2],L[-1],p) >= 0: L.pop()
        U.append(p)
        L.append(p)
    return U+L[1:-1][::-1]

In [159]:
def dist(p,q):
    return ((p[0]-q[0])**2+(p[1]-q[1])**2)
    

In [160]:
points=[(0,5),(1,8),(3,4),(5,0),(6,2),(6,6),(8,3),(8,7)]

In [161]:
qs=graham_scan(points)
res=0
for i in range(len(qs)):
    for j in range(i):
        res=max(res,dist(qs[i],qs[j]))
print (res )

80


In [138]:
qs

[(0, 5), (5, 0), (8, 3), (8, 7), (1, 8)]

In [151]:
from __future__ import generators

def orientation(p,q,r):
    '''Return positive number if p-q-r are clockwise, neg if ccw, zero if colinear.'''
    return (q[1]-p[1])*(r[0]-p[0]) - (q[0]-p[0])*(r[1]-p[1])

def hulls(Points):
    '''Graham scan to find upper and lower convex hulls of a set of 2d points.'''
    U = []
    L = []
    Points.sort()
    for p in Points:
        while len(U) > 1 and orientation(U[-2],U[-1],p) <= 0: U.pop()
        while len(L) > 1 and orientation(L[-2],L[-1],p) >= 0: L.pop()
        U.append(p)
        L.append(p)
    return U,L

# U,L = hulls([(0,0),(1,1),(0,1),(1,0),(1,3),(3,1),(2,2)])
# returns
# U = [(0, 0), (0, 1), (1, 3), (3, 1)]
# L = [(0, 0), (1, 0), (3, 1)]

def rotatingCalipers(Points):
    '''Given a list of 2d points, finds all ways of sandwiching the points between
two parallel lines that touch one point each, and yields the sequence of pairs of
points touched by each pair of lines.'''
    U,L = hulls(Points)
    i = 0
    j = len(L) - 1
    while i < len(U) - 1 or j > 0:
        yield U[i],L[j]
        
        # if all the way through one of top or bottom, advance the other
        if i == len(U) - 1: j -= 1
        elif j == 0: i += 1
        
        # still points left on both lists, compare slopes of next hull edges
        elif (U[i+1][1]-U[i][1])*(L[j][0]-L[j-1][0]) > \
                (L[j][1]-L[j-1][1])*(U[i+1][0]-U[i][0]):
            i += 1
        else: j -= 1

# rotatingCalipers([(0,0),(1,1),(0,1),(1,0),(1,3),(3,1),(2,2)])
# yields:
# (0, 0) (3, 1)
# (0, 1) (3, 1)
# (1, 3) (3, 1)
# (1, 3) (1, 0)
# (1, 3) (0, 0)

def diameter(Points):
    '''Given a list of 2d points, returns the pair that's farthest apart.'''
    bestPair = None
    bestDist = 0
    def square(x): return x*x
    for p,q in rotatingCalipers(Points):
        dist = square(q[0]-p[0]) + square(q[1]-p[1])
        if dist > bestDist:
            bestDist = dist
            bestPair = (p,q)
    return bestPair,bestDist

# diameter([(0,0),(1,1),(0,1),(1,0),(1,3),(3,1),(2,2)])
# returns: ((0, 0), (3, 1))

In [152]:
points=[(0,5),(1,8),(3,4),(5,0),(6,2),(6,6),(8,3),(8,7)]

In [153]:
diameter(points)

(((1, 8), (5, 0)), 80)

In [164]:
def simpson(func,a,b):
    return (b-a)/6*(func(a)+4*func((a+b)/2)+func(b))


In [172]:
inpt=iter([
'4 4',
'-98 99',
'-99 -99',
'99 -98',
'99 97',
'-99 99',
'-98 -98',
'99 -99',
'96 99'
    ])
m,n=tuple(map(int,next(inpt).split()))
def simpson(func,a,b):
    return (b-a)/6*(func(a)+4*func((a+b)/2)+func(b))

def width(points,x):
    #计算x 切过polygon的宽度
    # points are sorted ccw 
    lb=float('inf')
    ub=float('-inf')
    n=len(points)
    for i in range(n):
        x1,y1=points[i]
        x2,y2=points[(i+1)%n]
        if (x1-x)*(x2-x)<=0 and x1!=x2:
            y=y1+(y2-y1)*(x-x1)/(x2-x1)
            lb=min(lb,y)
            ub=max(ub,y)
    return max(0,ub-lb)

xs=[] # record every change of x 
z_polygon=[] 
for _ in range(m):
    point=tuple(map(int,next(inpt).split()))
    z_polygon.append(point)
    xs.append(point[0])
y_polygon=[]
for _ in range(n):
    point=tuple(map(int,next(inpt).split()))
    y_polygon.append(point)
    xs.append(point[0])

func=lambda x:width(z_polygon,x)*width(y_polygon,x)
xs.sort()
res=0
for i in range(len(xs)-1):
    a=xs[i]
    b=xs[i+1]
    res+=simpson(func,a,b)

print (res)


7600258.484771574
